### ISSUE TITLE
Sorted Model

### ISSUE THREAD

**Issue by webfalter** [notiflux/OpenCore-Configurator#1]
https://github.com/notiflux/OpenCore-Configurator/blob/b6d01e03d3efde192b12419a132aecac3044c290/OpenCore%20Configurator/ViewController.swift#L1296

`for model in Array(serialDict.keys).sorted(by:{$0.localizedStandardCompare($1) == .orderedAscending} ) {`

LG

**Comment by notiflux** [comment]
[merged](https://github.com/notiflux/OpenCore-Configurator/commit/d086c44b1a215ddf3271ad09bea897b582116bd3)
