### ISSUE TITLE
how can i set it up for i7-7800X?

### ISSUE THREAD

**Issue by ZISQO** [notiflux/OpenCore-Configurator#12]
hi there~ : )

my system build is ASUS X299 TUF MK1 with i7-700X
but stuck at AICPUPM even if include SSDT from ssdtPRGen already.

how can i set it up more than exactly my cpu type on Open Core?

**Comment by ReaperOfSouls1909** [comment]
We told you before opencore doesnt have fake cpu id yet

**Comment by ZISQO** [comment]
@ReaperOfSouls1909
ya i heard from discord yesterday, but I start the opinion that if I leave this opinion here, 
it will soon be supported fakecpuid by Developer! : )

**Comment by tonyarnold** [comment]
Except that this is the repository for the configurator app, not OpenCore itself.

**Comment by ZISQO** [comment]
@tonyarnold 
oh i see, my mistake! will you let me know where are OpenCore issue url?

**Comment by notiflux** [comment]
The issue trackers are for bugs in the software, not for user support. You should go to the support forum instead (I'm sure you'll find the InsanelyMac thread with a little googling)
